<Logback_Panel>:
    canvas:
        Color:
            rgba: 0.5,0.5,0.5,0.5
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: 0.2,0.2,0.2,0.5
        Rectangle:
            size: self.size[0] - 20, self.size[1] - 20
            pos: self.pos[0] + 10, self.pos[1] + 10
    cols:2
    size_hint_y:None
    row_default_height: 50
    Label:
        text: 'present!'
